# Generated by Django 3.1.7 on 2021-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_auto_20210324_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BinaryField(blank=True, default=False, null=True),
        ),
    ]
